---
title: "ACLU Child Separations"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
```

```{r}
# load data
aclu <- read_csv('aclu_separations.csv')
```

```{r}
# inspect data
head(aclu)
summary(aclu)
```

```{r}
# select columns
aclu <- aclu %>%
select(-addr)
```

```{r}
# view columns
colnames(aclu)
```

```{r}
# rename columns
aclu <- aclu %>%
rename(city = program_city,
      state = program_state,
      number_children = n,
      longitude = lon,
      latitude = lat)
colnames(aclu)
```

```{r}
# add column
aclu <- aclu %>%
mutate(border_latitude = 25.83)
```

```{r}
# latitude change
aclu <- aclu %>%
mutate(lat_change_border = latitude- border_latitude)

further_away <- aclu %>%
filter(lat_change_border > 15)
further_away

further_away <- further_away %>%
arrange(desc(lat_change_border))
further_away
```

```{r}
# number of children
ordered_by_children <- aclu %>%
arrange(desc(number_children))
ordered_by_children
```

```{r}
# state analysis
'''
Alabama: AL, Alaska: AK, Arizona: AZ, Arkansas: AR, California: CA, Colorado: CO, Connecticut: CT, Delaware: DE, Florida: FL, Georgia: GA, Hawaii: HI, Idaho: ID, Illinois: IL, Indiana: IN, Iowa: IA, Kansas: KS, Kentucky: KY, Louisiana: LA, Maine: ME, Maryland: MD, Massachusetts: MA, Michigan: MI, Minnesota: MN, Mississippi: MS, Missouri: MO, Montana: MT, Nebraska: NE, Nevada: NV, New Hampshire: NH, New Jersey: NJ, New Mexico: NM, New York: NY, North Carolina: NC, North Dakota: ND, Ohio: OH, Oklahoma: OK, Oregon: OR, Pennsylvania: PA, Rhode Island: RI, South Carolina: SC, South Dakota: SD, Tennessee: TN, Texas: TX, Utah: UT, Vermont: VT, Virginia: VA, Washington: WA, West Virginia: WV, Wisconsin: WI, Wyoming: WY
'''
chosen_state <- 'AZ'
chosen_state_separations <- aclu %>%
filter(state == chosen_state)
chosen_state_separations

chosen_state_separations <- chosen_state_separations %>%
arrange(desc(number_children))
chosen_state_separations
```