---
title: "Joining Tables in R"
output: html_notebook
---

```{r message = FALSE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE}
# load orders data
orders <- read_csv("orders.csv")
customers <- read_csv("customers.csv")
products <- read_csv("products.csv")
```

```{r}
# inspect orders, customers and products here:
head(orders)
head(customers) # same customer_id from orders
head(products) # same product_id from orders
```

```{r}
# define order_3_description here:
order_3_description <- products$description[products$product_id
== orders$product_id[orders$order_id==3]]

# define order_5_phone_number here:
order_5_phone_number <- customers$phone_number[customers$customer_id
== orders$customer_id[orders$order_id==5]]
```

```{r message = FALSE}
# load sales and targets data
sales <- read_csv("sales.csv")
targets <- read_csv("targets.csv")
```

```{r}
# inspect sales, and targets
head(sales)
head(targets)
```

```{r}
# define sales_vs_targets here:
sales_vs_targets <- sales %>%
inner_join(targets)

sales_vs_targets
```

```{r}
# define crushing_it here:
crushing_it <- sales_vs_targets %>%
filter(revenue > target)

crushing_it
```

```{r}
# load men_women data here:
men_women <- read_csv('men_women_sales.csv')

# inspect men_women here:
head(men_women)

```

```{r}
# define all_data here:
all_data <- sales %>%
inner_join(targets) %>%
inner_join(men_women)

all_data
```

```{r}
# define results here:
results <- all_data %>%
filter(revenue > target & women > men)

results
```

```{r}
# inspect orders and products
head(orders)
head(products)
```

Using Rename

```{r}
# rename the id column of products here:
products <- products %>%
rename(product_id = id)

products
```

```{r}
# define orders_products here:
orders_products <- orders %>%
inner_join(products)

orders_products
```

Using Suffix

```{r}
# define orders_products here:
orders_products <- orders %>%
inner_join(products, by = c('product_id'='id'), suffix = c('_orders','_products'))

orders_products
```

```{r}
# define products_orders here:
products_orders <- products %>%
inner_join(orders, by = c('id' = 'product_id'), suffix=c('_product','_order'))

products_orders
```

Missing Data on Orders (product_id is new)

```{r}
# inspect orders and products here:
head(orders)
head(products)
```

```{r}
# define orders_products here:
orders_products <- orders %>%
inner_join(products)

orders_products
## order_id = 3 is dropped
```

full join

```{r message = FALSE}
# load store_a and store_b data
store_a <- read_csv("store_a.csv")
store_b <- read_csv("store_b.csv")
```

```{r}
# inspect store_a and store_b
head(store_a)
head(store_b)
```

```{r}
# define store_a_b_full here:
store_a_b_full <- store_a %>%
full_join(store_b)

store_a_b_full
```

left join

```{r}
# define left_a_b here:
left_a_b <- store_a %>%
left_join(store_b)

left_a_b
```

```{r}
# define left_b_a here:
left_b_a <- store_b %>%
left_join(store_a)

left_b_a
```

```{r message = FALSE}
# load bakery and ice_cream data
bakery <- read_csv('bakery.csv')
ice_cream <- read_csv('ice_cream.csv')
```

```{r}
# inspect bakery and ice_cream
head(bakery)
head(ice_cream)
```

```{r}
# define menu here:
menu <- bakery %>%
bind_rows(ice_cream)

menu
```

```{r message = FALSE}
# load visits and checkouts data
visits <- read_csv('visits.csv')
checkouts <- read_csv('checkouts.csv')
```

```{r}
# inspect visits and checkouts here:
head(visits)
head(checkouts)
```

```{r}
# define v_to_c here:
v_to_c <- visits %>%
inner_join(checkouts)

v_to_c

v_to_c <- v_to_c %>%
mutate(time = checkout_time - visit_time)

v_to_c
```

```{r}
# define avg_time_to_check here:
avg_time_to_check <- v_to_c %>%
summarize(mean_time = mean(time))

avg_time_to_check
```
