---
title: "Introduction to Data Frames"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
```

```{r}
# load data frame
artists <- read_csv('artists.csv')
```

```{r}
# inspect data frame
artists
head(artists)
summary(artists)
```

```{r}
# select columns, filter and arrange rows of artists
artists_manipulated <- artists %>% 
  select(-country,-year_founded,-albums) %>% 
  filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop') %>% 
  arrange(desc(youtube_subscribers))
artists_manipulated
```

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
```

```{r}
# load data frame
songs <- read_csv('songs.csv')
```

```{r}
songs
```
```{r}
artists <- read_csv('artists.csv')
```

```{r}
# inspect data frame
artists
head(artists)
summary(artists)
```

```{r}
# inspect data frame with pipe
artists %>%
	head()

```

```{r}
# select one column
artist_groups <- select(artists,group)
artist_groups
```

```{r}
# select multiple columns
group_info <- select(artists,group,spotify_monthly_listeners,year_founded)
group_info
```

```{r}
# select all columns except one
no_albums <- artists %>%
select(-albums)
no_albums

```

```{r}
# select all columns except a set
df_cols_removed <- artists %>%
select(-genre,-spotify_monthly_listeners,-year_founded)
df_cols_removed
```

```{r}
# filter rows one condition
rock_groups <- artists %>%
filter(genre=='Rock')
rock_groups
```

```{r}
# filter rows multiple conditions
popular_rock_groups <- artists %>%
filter(genre=='Rock', spotify_monthly_listeners > 20000000)
popular_rock_groups
```

```{r}
# filter rows with or
korea_or_before_2000 <- artists %>%
filter(country=='South Korea'|year_founded < 2000)
korea_or_before_2000
```

```{r}
# filter rows with not !
not_rock_groups <- artists %>%
filter(!(genre=='Rock'))
not_rock_groups
```

```{r}
# arrange rows in ascending order
group_asc <- artists %>%
arrange(group)
group_asc
```

```{r}
# arrange rows in descending order
youtube_desc <- artists %>%
arrange(desc(youtube_subscribers))
youtube_desc
```

Review

```{r}
# select columns
chosen_cols <- artists %>% 
  select(-country,-year_founded,-albums)
head(chosen_cols)
```

```{r}
# filter rows
popular_not_hip_hop <- chosen_cols %>% 
  filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop') 
head(popular_not_hip_hop)
```

```{r}
# arrange rows
youtube_desc <- popular_not_hip_hop %>% 
  arrange(desc(youtube_subscribers))
head(youtube_desc)
```

```{r}
# select columns, filter and arrange rows
artists <- artists %>%
	select(-country,-year_founded,-albums) %>%
	filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop') %>%
	arrange(desc(youtube_subscribers))
head(artists)
```
