---
title: "Hypothesis Testing in R"
output: html_notebook
---

```{r}
# generate random population
population <- rnorm(300, mean=65, sd=3.5)

# calculate population mean here:
population_mean <- mean(population)
population_mean
```

```{r}
# generate sample 1
sample_1 <- sample(population, size=30)
sample_1

# calculate sample 1 mean
sample_1_mean <- mean(sample_1)
sample_1_mean
```

```{r}
# generate samples 2,3,4 and 5
sample_2 <- sample(population, size=30)
sample_3 <- sample(population, size=30)
sample_4 <- sample(population, size=30)
sample_5 <- sample(population, size=30)
```

```{r}
# calculate sample means here:
sample_2_mean <- mean(sample_2)
sample_2_mean
sample_3_mean <- mean(sample_3)
sample_3_mean
sample_4_mean <- mean(sample_4)
sample_4_mean
sample_5_mean <- mean(sample_5)
sample_5_mean
```

```{r}
# experiment 1
hypo_a <- "DeePressurize lowers blood pressure in patients."
hypo_b <- "DeePressurize has no effect on blood pressure in patients."
null_hypo_1 <- 'hypo_b'
```

```{r}
# experiment 2
hypo_c <- "The new profile layout has no effect on number of matches with other users."
hypo_d <- "The new profile layout results in more matches with other users than the original layout."
null_hypo_2 <- 'hypo_c'
```
```{r}
# load data
load("retriever_lengths.Rda")
load("doodle_lengths.Rda")
```

```{r}
# calculate mean_retriever_l and mean_doodle_l here:
mean_retriever_l <- mean(retriever_lengths)
mean_doodle_l <- mean(doodle_lengths)
```

```{r}
# calculate mean_difference here:
mean_difference <- mean_retriever_l - mean_doodle_l
```

```{r}
# statements:
st_1 <- "The average length of Golden Retrievers is 2.5 inches longer than the average length of Goldendoodles."
st_2 <- "The average length of Golden Retrievers is the same as the average length of Goldendoodles."

# update null_hypo here:
null_hypo <- "st_2
```


```{r}
# the true positives and negatives:
actual_positive <- c(2, 5, 6, 7, 8, 10, 18, 21, 24, 25, 29, 30, 32, 33, 38, 39, 42, 44, 45, 47)
actual_negative <- c(1, 3, 4, 9, 11, 12, 13, 14, 15, 16, 17, 19, 20, 22, 23, 26, 27, 28, 31, 34, 35, 36, 37, 40, 41, 43, 46, 48, 49)

# the positives and negatives we determine by running the experiment:
experimental_positive <- c(2, 4, 5, 7, 8, 9, 10, 11, 13, 15, 16, 17, 18, 19, 20, 21, 22, 24, 26, 27, 28, 32, 35, 36, 38, 39, 40, 45, 46, 49)
experimental_negative <- c(1, 3, 6, 12, 14, 23, 25, 29, 30, 31, 33, 34, 37, 41, 42, 43, 44, 47, 48)
```

```{r}
# define type_i_errors and type_ii_errors here:
type_i_errors <- intersect(experimental_positive,actual_negative)

type_ii_errors <- intersect(experimental_negative,actual_positive)
```

```{r}
# possible interpretations
st_1 <- "There is a 20% chance that the difference in average weight of green and red apples is due to random sampling."
st_2 <- "There is a 20% chance that green and red apples have the same average weight."
st_3 <- "There is a 20% red apples weight more than green apples."
st_4 <- "There is a 20% green apples weight more than green apples."

# update the value of interpretation here:
interpretation <- "st_1"
```

Before you run a hypothesis test on a set of data, you set your significance level to 0.05. The hypothesis test then returns a p-value of 0.1. Can you reject the null hypothesis? Update the value of reject_hypothesis to TRUE or FALSE depending on your answer.

```{r}
# update reject_hypothesis here:
reject_hypothesis <- FALSE
```

```{r message = FALSE}
# load and view data
load("ages.Rda")
ages
```

```{r}
# calculate ages_mean here:
ages_mean <- mean(ages)
ages_mean
```

```{r}
# perform t-test here:
results <- t.test(ages,mu = 30)
results
# not reject null hypothesis
```

```{r message = FALSE}
# load data
load("week_1.Rda")
week_1
load("week_2.Rda")
week_2
```

```{r}
# calculate week_1_mean and week_2_mean here:
week_1_mean <- mean(week_1)
## 25.44806
week_2_mean <- mean(week_2)
## 29.02157
```

```{r}
# calculate week_1_sd and week_2_sd here:
week_1_sd <- sd(week_1)
week_2_sd <- sd(week_2)
```

```{r}
# run two sample t-test here:
results <- t.test(week_1, week_2)
results
## reject null hypothesis
```

```{r message = FALSE}
# load data
load("store_a.Rda")
load("store_b.Rda")
load("store_c.Rda")
```

```{r}
# calculate means here:
store_a_mean <- mean(store_a)
store_a_mean
store_b_mean <- mean(store_b)
store_b_mean
store_c_mean <- mean(store_c)
store_c_mean
```

```{r}
# calculate standard deviations here:
store_a_sd <- sd(store_a)
store_b_sd <- sd(store_b)
store_c_sd <- sd(store_c)
```

```{r}
# perform two sample t-test here:
a_b_results <- t.test(store_a,store_b)
a_b_results ## reject null (99%)
a_c_results <- t.test(store_a,store_c)
a_c_results ## reject null (95%)
b_c_results <- t.test(store_b,store_c)
b_c_results ## reject null (90%)
```

```{r}
# calculate error_prob here:
error_prob <- (1-(0.95**3))
error_prob
```

```{r message = FALSE}
# load data
load("stores.Rda")
load("stores_new.Rda")
```

```{r}
# inspect stores here:
stores
```

```{r}
# perform anova on stores here:
results <- aov(sales ~ store, data = stores)
summary(results)
## reject null hypothesis
```

```{r}
# perform anova on stores_new here:
results_new <- aov(sales ~ store, data = stores_new)
summary(results_new)
## reject null hypothesis
```

```{r message = FALSE}
# load data
load("dist_one.Rda")
load("dist_two.Rda")
load("dist_three.Rda")
load("dist_four.Rda")
```

```{r}
# plot histograms and define not_normal here:
hist(dist_one)
hist(dist_two)
hist(dist_three)
hist(dist_four)

not_normal <- 4
```

```{r}
# define ratio here:
ratio <- sd(dist_two) / sd(dist_three)
ratio
## 0.5784 : not close to 1
```