---
title: "Modifying Data Frames in R"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
```

```{r}
# load data frame
setwd('/Users/EternalFlow/Desktop/developer/R_Analytics/R_Practice/CodeAcademy')
dogs <- read_csv('dogs.csv')
```

```{r}
# inspect data frame
head(dogs)
```

```{r}
# rename columns
dogs <- dogs %>%
  rename(popularity_2016 = rank_2016,
        popularity_2015 = rank_2015,
        popularity_2014 = rank_2014,
        popularity_2013 = rank_2013)
colnames(dogs)
```

```{r}
# calculate average height, average weight, and change in popularity from 2013 to 2016
dogs <- dogs %>%
  transmute(breed = breed,
            avg_height = (height_low_inches + height_high_inches)/2,
            avg_weight = (weight_low_lbs + weight_high_lbs)/2,
            pop_change_13_to_16 = popularity_2016 - popularity_2013)
head(dogs)
```

Start from here

```{r}
# load data frame
dogs <- read_csv('dogs.csv')
```

```{r}
# inspect data frame
head(dogs)
```
```{r}
# add average height, average weight and rank change columns
dogs <- dogs %>%
  mutate(avg_height = (height_low_inches + height_high_inches)/2,
        avg_weight = (weight_low_lbs+weight_high_lbs)/2,
        rank_change_13_to_16 = rank_2016 - rank_2013)
head(dogs)
```

```{r}
# update the function call to drop all existing columns
dogs <- dogs %>%
  transmute(breed = breed, avg_height = (height_low_inches + height_high_inches)/2,
         avg_weight = (weight_low_lbs + weight_high_lbs)/2,
        rank_change_13_to_16 = rank_2016 - rank_2013)
head(dogs)
```

```{r}
# check column names
original_col_names <- colnames(dogs)
print(original_col_names)
```

```{r}
# rename data frame columns
dogs <- dogs %>%
rename(avg_height_inches = avg_height,
        avg_weight_lbs = avg_weight,
        popularity_change_13_to_16 = rank_change_13_to_16)
```

```{r}
# check column names
new_col_names <- colnames(dogs)
print(new_col_names)
```

```{r message=FALSE}
# load data frame
dogs <- read_csv('dogs.csv')
```

```{r}
# inspect data frame
head(dogs)
```

```{r}
# add new columns, drop existing columns and arrange
dogs <- dogs %>%
transmute(breed = breed,
height_average_feet = (height_low_inches+height_high_inches)/2/12,
popularity_change_15_to_16 = rank_2016 - rank_2015) %>%
arrange(desc(popularity_change_15_to_16))
head(dogs)
```